### ISSUE TITLE
Refactor macro to inline function

### ISSUE THREAD

**Issue by HowJMay** [DLTcollab/sse2neon#131]
Some implementations are macros instead of inline functions (e.g. [_mm_slli_epi32](https://github.com/DLTcollab/sse2neon/blob/master/sse2neon.h#L1678)). Should we refactor them into inline functions for consistency?

**Comment by HowJMay** [comment]
@jserv @marktwtn how are your opinions?

**Comment by jserv** [comment]
According to [Intel Intrinsic Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_slli_epi16), the last parameter of `_mm_slli_epi16` is `imm8`, which can not be a variable. You can only pass Numeric  constants for such immediate values. That is why we implement these intrinsics in macro instead of inline functions.

**Comment by jserv** [comment]
Let's close this issue. It can be reopen when we get new ideas.
