### ISSUE TITLE
_mm_movemask_epi8 regression

### ISSUE THREAD

**Issue by jacksonrnewhouse** [DLTcollab/sse2neon#219]
The aarch64 code path for _mm_movemask_epi8 introduced in #50 looks to be a regression when you actually compile it. The default behavior compiles to 7 instructions with no constants, while the "fast path" is 14 instructions plus a constant. Should it be reverted?

fast path: https://godbolt.org/z/41s54d
default: https://godbolt.org/z/xsYfz8

**Comment by marktwtn** [comment]
I'll make a simple time experiment of `_mm_movemask_epi8`.

**Comment by marktwtn** [comment]
I do the experiment on the `ARMv8-A` CPU, which is an ARM 64-bit architecture.

![graph](https://user-images.githubusercontent.com/6748200/104891699-42821380-59ac-11eb-87fc-7f190f26358d.png)

It turns out that the aarch64 code path does behave worse.
We should revert it for performance consideration.

**Comment by marktwtn** [comment]
The performance of optimization level 3 is measured as well.

![graph](https://user-images.githubusercontent.com/6748200/105315980-2b853080-5bfb-11eb-9abb-1a53e36d4c80.png)

The performance does not have too much difference.
@jserv I think we need to decide which optimization level we should focus on for the future performance improvement.
