### ISSUE TITLE
improve _mm_set_epi64x

### ISSUE THREAD

**Issue by wangxiao1254** [DLTcollab/sse2neon#229]
Thanks for providing such a great tool!

The current implementation of `_mm_set_epi64x` uses an array. It might be better to use `vcombine_u64` when it is available?

**Comment by jserv** [comment]
> vcombine_u64

Did you mean the following code snip?
```c
#define _mm_set_epi64x(u1, u0) \
    (__m128i) vcombine_u64(vcreate_u64(u0), vcreate_u64(u1))
```

I am not sure if the later would be faster or not.

**Comment by wangxiao1254** [comment]
That's what I meant.

**Comment by jserv** [comment]
We might evaluate both `_mm_set_epi64x` and `_mm_set_epi64` as well.

**Comment by marktwtn** [comment]
I have done the experiment of `_mm_set_epi64x` on `ARMv8-A` CPU.

![graph](https://user-images.githubusercontent.com/6748200/104901657-a3174d80-59b8-11eb-84d6-cb899a351b1d.png)

It turns out that the performance of using array is slightly worse than using `vcreate()` sometimes.
I will do another experiment of `_mm_set_epi64` and send a pull request.

**Comment by marktwtn** [comment]
The assembly code comparison of the `_mm_set_epi64x`: https://godbolt.org/z/KP9Ga4

The one with `vcreate()` uses 3 assembly instructions, while the other one with array uses 5 assembly instructions.

**Comment by wangxiao1254** [comment]
Does efficiency matter in O0 :)

**Comment by marktwtn** [comment]
I also did the experiment with optimization level 3.

![graph](https://user-images.githubusercontent.com/6748200/105302695-5325ca00-5bf6-11eb-99bc-50bbfb0a11e7.png)

The performance does not have too much difference.
However, consider of the performance on optimization level 0, we can still take the modification.
