### ISSUE TITLE
Implement _mm_aesenclast_si128

### ISSUE THREAD

**Issue by liorko87** [DLTcollab/sse2neon#5]
Hello,

Is there an implementation for `_mm_aesenclast_si128` instruction?
When I'm trying to compile my program, I'm getting this error:
`_mm_aesenclast_si128 was not declared in this scope`

Lior

**Comment by marktwtn** [comment]
We do not have the `_mm_aesenclast_si128` implementation
since it is in the **AES**`(Advanced Encryption Standard)` instruction set, as shown in the [Intel Intrinsic Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesenclast_si128&expand=236).

The repository is mainly for the conversion from **SSE** to **NEON** instruction set.

**Comment by jserv** [comment]
Reopen since `sse2neon` project is emulating x86 AES Intrinsics on A32/A64.

**Comment by jserv** [comment]
`_mm_aesenclast_si128` can be implemented via crypto extension for A64:
```c
// https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_aesenclast_si128
FORCE_INLINE __m128i _mm_aesenclast_si128(__m128i a, __m128i RoundKey)
{
    return vaeseq_u8(a, (__m128i){}) ^ RoundKey;
}
```
