### ISSUE TITLE
AVX support? 

### ISSUE THREAD

**Issue by appwagner** [DLTcollab/sse2neon#507]
Thanks very much for creating this useful project. I'm trying to convert some code that uses AVX instructions using _m256d registers and it doesn't look like this type is handled in the current version of sse2neon. Thanks again for your help.

**Comment by jserv** [comment]
As the project name implies, SSE2NEON tends to provide SSE coverage rather than AVX. You can use [SIMDe](https://github.com/simd-everywhere/simde) for generic AVX support. Also, you can browse the source code of [embree](https://github.com/embree/embree) to check how AVX code is mapped to Arm NEON counterpart.

**Comment by appwagner** [comment]
Thanks for the references. I'm actually porting this code on an M1 mac so it may be better to use the Apple Accelerate frame work from the start for my use case.
